### PR TITLE
Nonpublic methods that don't access any instance members were made `static`

### PR DESCRIPTION
**Pull request by Lehonti**

### CODE REVIEW

**Comment by jpobst** [comment]
Thanks for the PR, but I think I'm going to pass.  I don't want to spend the effort auditing these to see if I actually want them to be static or not.

**Comment by Lehonti** [comment]
I like to compare _private_ or _internal_ `static` methods to _private_ or _internal_ fields the `readonly` keyword. Even if the methods are `static` by accident, the keyword is telling you something about them, and it's giving you some guarantees; also, if you want the methods access instance members, removing the keyword is just as easy. What do you think?

**Comment by TheColonel2688** [comment]
@Lehonti  

you should google "bike shedding"

**Comment by Lehonti** [comment]
@TheColonel2688 a small change like this is almost meaningless by itself, but if you combine it with many other improvements it can result in a codebase with an enormously improved quality

**Pull request closed without merging**
